export const Data = [
    {
      id: 'm1',
      name: 'The Devil',
      type: 'Cream Prestyle',
      price: 22.99,
      img:'https://pomadziarz.pl/userdata/public/gfx/4020/lockhart-the-devil-prestyler.webp',
      author:'Lockharts',
    },
    {
      id: 'm2',
      name: 'Antigravity',
      type: 'Cream pomade',
      price: 12.99,
      img:'https://dlagentlemana.pl/userdata/public/gfx/5459/Lockharts-mike-hrubovak-anti-gravity.jpg',
      author:'Lockharts',
    },
    {
      id: 'm3',
      name: 'Goon Grease',
      type: 'Water based pomade',
      price: 17.99,
      img:'https://dlagentlemana.pl/userdata/public/gfx/14052/LOCK-GG-113-1-1.png',
      author:'Lockharts',
    },
  
    {
      id: 'm4',
      name: 'Matte Clay',
      type: 'Clay Pomade',
      price: 15.99,
      img: 'https://beardman.pl/environment/cache/images/500_500_productGfx_14530/lockharts-matte-clay-pomada-do-wlosow-105g-1.webp',
      author:'Lockharts',
    },
    {
      id: 'm5',
      name: 'Fire & Brimstone',
      type: 'Pomade',
      price: 19.99,
      img: 'https://dlagentlemana.pl/userdata/public/gfx/5261/lockhart_s_fire_brimstone_water_based.jpg',
      author:'Lockharts',
    },
    {
      id: 'm6',
      name: 'Blue LaGoon ',
      type: 'Hair Tonic',
      price: 8.99,
      img: 'https://beardman.pl/environment/cache/images/500_500_productGfx_14940/lockharts-blue-lagoon-tonik-do-wlosow-118ml-1.webp',
      author:'Lockharts',
    },
    {
      id: 'm7',
      name: 'Classic Pomade',
      type: 'Pomade',
      price: 14.99,
      img: 'https://afterbarber.pl/wp-content/uploads/2021/03/lockhh-600x600.jpg',
      author:'Lockharts',
    },
    {
      id: 'm8',
      name: 'Grooming Cream',
      type: 'Grooming Cream',
      price: 11.99,
      img: 'https://barbercompany.pl/image/cache/wp/gj/2020/09-2020/Lockharts-Groom-Cream-105g-543x543.webp',
      author:'Lockharts',
    },
    {
      id: 'm9',
      name: 'Untouchable ',
      type: 'Hair Pomade',
      price: 16.99,
      img: 'https://afterbarber.pl/wp-content/uploads/2021/03/UNTOUCHABLE-Lockhartx-X-Capone-600x600.jpg',
      author:'Lockharts',
    },
    {
      id: 'm10',
      name: 'Light Hold Wax',
      type: 'Wax',
      price: 13.99,
      img: 'https://static1.mintishop.pl/pol_pm_Lockharts-Light-Hold-pomada-do-wlosow-113g-43404_1.webp',
      author:'Lockharts',
    },
    {
      id: 'm11',
      name: 'Strong Hold Paste',
      type: 'Hair Paste',
      price: 18.99,
      img: 'https://m.media-amazon.com/images/I/810u3oYS8fL._AC_UF1000,1000_QL80_.jpg',
      author:'Lockharts',
    },
    {
      id: 'm12',
      name: 'Sex machine',
      type: 'Hair paste',
      price: 29.99,
      img: 'https://a.allegroimg.com/s1024/0c152b/8007539d44f1b1fa21b46e711c42',
      author:'Lockharts',
    },
    {
      id: 'm13',
      name: 'Enigma',
      type: 'Creamy Prestyler',
      price: 9.99,
      img: 'https://dlagentlemana.pl/environment/cache/images/500_500_productGfx_4814/Lokcharts-Enigma-Volumizing-Cream-krem-do-wlosow-226g.jpg',
      author:'Lockharts',
    },
    {
        id: 'm14',
        name: 'Unorthodox Goon',
        type: 'Water based pomade',
        price: 11.99,
        img: 'https://afterbarber.pl/wp-content/uploads/2021/10/Lockharts-UWB-GOON-GREASE-600x600.jpg',
        author:'Lockharts',
    },
    {
        id: 'm15',
        name: 'Lion Tamer',
        type: 'Water based pomade',
        price: 16.99,
        img: 'https://dlagentlemana.pl/userdata/public/gfx/14283/lion-og-1.jpg',
        author:'Lockharts',
    },
    {
        id: 'm16',
        name: 'Phantasm',
        type: 'Sculpting Cream',
        price: 10.99,
        img: 'https://dlagentlemana.pl/userdata/public/gfx/4822/Lockharts-Phantasm-Sculpting-Cream-pomada-do-wlosow-35g-1.jpg',
        author:'Lockharts',
    },



    {
        id: 'm17',
        name: 'Meraki',
        type: 'Cream paste',
        price: 29.99,
        img: 'https://dlagentlemana.pl/userdata/public/gfx/3996/Pomada-do-wlosow-BluMaan-Original-Natural-Finish-74-ml-4.jpg',
        author:'BluMaan',
    },
    {
        id: 'm18',
        name: 'Monarch',
        type: 'Cream paste',
        price: 29.99,
        img: 'https://dlagentlemana.pl/userdata/public/gfx/3966/Pomada-do-wlosow-BluMaan-Monarch-74-ml.jpg',
        author:'BluMaan',
    },
    {
        id: 'm19',
        name: 'Fifth Sample',
        type: 'Cream paste',
        price: 25.99,
        img: 'https://dlagentlemana.pl/userdata/public/gfx/4007/Pomada-do-wlosow-BluMaan-Cavalier-Heavy-Clay-74-ml-3.jpg',
        author:'BluMaan',
    },
    {
        id: 'm20',
        name: 'Cavalier',
        type: 'Cream paste',
        price: 29.99,
        img: 'https://dlagentlemana.pl/userdata/public/gfx/3959/Pomada-do-wlosow-BluMaan-Fifth-Sample-Low-Shine-Edition-109-ml-3.jpg',
        author:'BluMaan',
    },
    {
        id: 'm21',
        name: 'Ascend',
        type: 'Volume Cream',
        price: 30.99,
        img: 'https://dlagentlemana.pl/userdata/public/gfx/7377/avc.jpg',
        author:'BluMaan',
    },
    {
        id: 'm22',
        name: 'Fiber',
        type: 'Water based pomade',
        price: 9.99,
        img: 'https://dlagentlemana.pl/environment/cache/images/500_500_productGfx_de6ab88bc493342ac16a5eadbdd05fc8.jpg',
        author:'Reuzel',
    },
    {
        id: 'm23',
        name: 'Surf Tonic',
        type: 'Sea salt spray',
        price: 8.99,
        img: 'https://dlagentlemana.pl/environment/cache/images/500_500_productGfx_a75a35e467039c529ec4da40f42681c0.jpg',
        author:'Reuzel',
    },
    {
        id: 'm24',
        name: 'Blue',
        type: 'Water pomade',
        price: 20.99,
        img: 'https://dlagentlemana.pl/environment/cache/images/500_500_productGfx_98127762120489e82563c9c282361dea.jpg',
        author:'Reuzel',
    },





  
  ];